name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: Test & Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          preCommands: npm run test
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
